config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :items do 
      member do 
        get :edit_join
        put :update_join 
      end 
    end 
  end 

  resources :users, :only => [:new, :create]

  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'

  

  root 'lists#index'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
    belongs_to :category
    belongs_to :item

    def item_name
        item.description
    end 

    def category_name
        category.name
    end 

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categorizations, dependent: :destroy
    has_many :items, :through => :categorizations 
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
    has_many :categorizations 
    has_many :categories, :through => :categorizations 
    validates :description, :presence => true, length: { maximum: 30 }
    accepts_nested_attributes_for :categorizations 

    STATUS = {
        :complete => true,
        :incomplete => false 
    }

    def complete?
        self.status == STATUS[:complete]
    end 

    def incomplete?
        self.status == STATUS[:incomplete]
    end 

    

end

app/models/list.rb
class List < ApplicationRecord
    has_many :items, dependent: :destroy
    belongs_to :user 
    validates :name, :presence => true, length: { maximum: 30 }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :lists, dependent: :destroy
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    def self.find_or_create_by_omniauth(auth_hash)
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end 
    end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def authentication_required
        if !logged_in?
            redirect_to login_path
        end 
    end 

    def logged_in?
        !!current_user 
    end 

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end 
    helper_method :current_user 

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)

    if @item.save
      redirect_to list_path(@list)
    else 
      render "lists/show"
    end 
  end

  def update 
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to list_item_url
    else
      redirect_to list_path(@item.list)
    end 
  end 

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end 

  def edit_join
    @item = Item.find(params[:id]) 
  end 

  def destroy
    @item = Item.find(params[:id]) 
    @item.destroy 

    redirect_to list_path(@item.list) 
  end 

  private
    
    def item_params 
      params.require(:item).permit(:description, :status, :category_ids => [], :categorization_ids => [], :categorizations_attributes => {})
    end 

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authentication_required 

    def index
        @list = List.new 
        @lists = @current_user.lists 
    end 

    def show
        @list = List.find(params[:id])
        @item = Item.new 
    end 

    def create
        user = @current_user 
        @list = user.lists.build(list_params)
        if @list.save 
            redirect_to list_url(@list)
        else 
            @lists = @current_user.lists      
            render :index 
        end 
    end 

    def destroy
        @list = List.find(params[:id]) 
        @list.destroy 

        redirect_to '/lists'
    end 

    private

        def list_params
            params.require(:list).permit(:name)
        end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end 

    def create
        if auth_hash = request.env["omniauth.auth"]
            user = User.find_or_create_by_omniauth(auth_hash)  
            session[:user_id] = user.id 

            redirect_to root_path 
        else 
            user = User.find_by(:email => params[:email]) 
            if user && user.authenticate(params[:password])
                session[:user_id] = user.id 

                redirect_to root_path 
            else 
                render 'sessions/new'
            end
        end 
    end 

    def destroy
        reset_session
        redirect_to login_path
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

    def new 
        @user = User.new 
    end 

    def create
        @user = User.new 
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        if @user.save
            session[:user_id] = @user.id 
            redirect_to root_path
        else 
            render 'users/new' 
        end  
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

    def li_class_for_item(item)
        "completed" if item.complete?
    end 

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item_li.html.erb
<li class="<%= li_class_for_item(item) %>">
    <div class="view">
        <%= form_for([@list, item]) do |f| %>
            <%= f.hidden_field :status, value: !item.complete? %>
            <%= f.submit item.complete? ? "Mark incomplete." : "Mark complete." %>
        <% end %> 

        <label><%= link_to item.description, list_item_path(item.list, item) %></label>

        <%= button_to "X", list_item_path(item.list, item), :method => "delete", :class => "destroy" %>

    </div>
</li> 

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<h1><u>Editing Item</u></h1> 

<h1><%= @item.description %></h1>



<%= form_for @item, url: {action: "update"} do |f| %>
    <% if @item.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
  
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :status %><br />
      <%= f.text_field :status %>
    </div>

    <div>
        <h4>Item Categories:</h4>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
            <p>
                <%= b.label %>
                <%= b.check_box %>
            </p>
        <% end %> 
    </div>

    <div>
      <h4>Check which category is fragile:</h4>
      <%= f.fields_for :categorizations, @item.categorizations do |ff| %>
        <p>
          <%= ff.object.category_name %> 
          <%= ff.label :fragile %>
          <%= ff.check_box :fragile %>
        </p> 
      <% end %>
    </div> 

    <div class="actions">
    <%= f.submit 'Update Item' %>
    </div>
<% end %>



<p>
<%= link_to "Back to item.", list_item_path %>  
<br>
<%= link_to "Back to list.", @item.list %>
</p>

app/views/items/edit_join.html.erb
<h1><u>Editting Item</u></h1> 

<h1><%= @item.description %></h1>

<%= form_for @item, url: {action: "update"} do |f| %>
    <% if @item.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
  
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<div>
    <h4>For this item, check which category is fragile:</h4>
    <%= f.fields_for :categorizations, @item.categorizations do |ff| %>
    <p>
        <%= ff.object.category_name %> 
        <%= ff.label :fragile %>
        <%= ff.check_box :fragile %>
    </p> 
    <% end %>
</div> 

<div class="actions">
    <%= f.submit 'Update Item' %>
</div>
<% end %>

<p>
<%= link_to "Back to item.", list_item_path %>  
<br>
<%= link_to "Back to list.", @item.list %>
</p>

app/views/items/show.html.erb
<h1><%= @item.description %></h1>
<p><h2>Status:</h2> <%= @item.status ? "Complete!" : "Not complete yet." %></p>

<h3>Categories:</h3>
<ul>
    <% @item.categories.each do |category| %>
        <li><%= category.name %></li>
    <% end %> 
</ul>

<h4>Item fragility depending on category:</h4>
<ul>
        <% @item.categorizations.each do |categorization| %>
            <li><%= categorization.category_name %> (<%= categorization.fragile ? "Yes" : "No" %>)</li>
        <% end %> 
</ul>

<p>
<%= link_to "Edit this item.", edit_list_item_path(@item) %>
<br>
<%= link_to "Edit this items' fragility.", edit_join_list_item_path(@item) %> 
<br> 
<%= link_to "Back to list.", @item.list %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
    <header class="header">
        <h1>Your Lists</h1>
        <%= form_for(@list) do |f| %>
            <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a name for your new list.") %>
            <%= f.submit :style => "display: none" %> 
        <% end %> 
    </header>
    
	<section class="main">  
        <ul class="todo-list">
            <% @lists.each do |list| %>
            <li>
                <div class="view">
                    <label><%= link_to list.name, list_path(list) %></label>
                    <%= button_to "X", list_path(list), :method => "delete", :class => "destroy" %>
                </div>
            </li>
            <% end %> 
        </ul>
    </section>
    <footer class="info">
        <p>Logged in as: <%= current_user.email %></p>
        <p><%= link_to "Logout", logout_path %></p>
    </footer>
</section>
						

app/views/lists/show.html.erb
<section class="todoapp">
    <header class="header">
        <h1><%= @list.name %></h1>
        <%= form_for([@list, @item]) do |f| %>
            <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item.") %>
            <%= f.submit :style => "display: none" %> 
        <% end %> 
    </header>
    
	<section class="main">
        <ul class="todo-list">
            <% @list.items.each do |item| %>
                <%= render :partial => "items/item_li", :locals => {:item => item} %>
            <% end %>
            <%= link_to "Back to all my lists.", '/lists' %>
        </ul>
    </section>
</section> 

app/views/users/new.html.erb
<section class="todoapp">
    <header class="header">
        <h1>Sign Up</h1>
        <%= form_for(@user) do |f| %> 
            <%= f.text_field :email, :class => "new-todo", :placeholder => (@user.errors.full_messages_for(:email).first || "Register with your e-mail.") %>
            <%= f.password_field :password, :class => "new-todo", :placeholder => (@user.errors.full_messages_for(:password).first || "Choose your password.") %>
            <%= f.submit %> 
        <% end %> 
    </header>

    <p><%= link_to "Already signed up? Login here!", "/login" %></p>
</section> 